version: '2.2'
services:
  jupyter-lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./app:/app
    environment:
      - JUPYTER_TOKEN=
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
